### ISSUE TITLE
Uncaught TypeError: Cannot read property 'selectionStart' of null

### ISSUE THREAD

**Issue by mertbulan** [ademilter/github-markupdown#1]
Eklenti var olan bir issue'ya yorum yazınca çalışıyor ancak yeni bir issue ekleyince çalışmıyor ve bu şekilde hata veriyor. Nedeni de yeni issue açarken kullanılan textarea'nın ID'sinin (issue_body) farklı olması.

**Comment by ademilter** [comment]
@semihxx'in kodları bi çok sorunu giderdi #2 :+1:

**Comment by mertbulan** [comment]
Birçok sorun giderilmiş ancak bahsettiğim sorun giderilmemiş. Ben düzelttim şimdi. #3
